### ISSUE TITLE
Can't open database

### ISSUE THREAD

**Issue by pottcpp** [jobe-m/ownkeepass#96] opened 2015-05-26 12:12 UTC
Since the "Store" is limited for feedback, I'll continue here:

I've a 1.x database on my sd-card and can't open it. The very same database opens on Windows, OS X and Blackberry OS.
It has opened on Jolla with one of the first versions of the OS and OwnKeePass, too.

Yes, I've verified that the password is correctly entered,

**Comment by jobe-m** [comment] 2015-05-26 13:56
Thx for coming back here. I will try to reproduce it.
Please provide me more details:

- Which Keepass Application was used to create the database? OwnKeepass, KeepassX 0.4.3, original Keepass 1 or another 3rd party Keepass application.
- How is your SD card formatted? (Fat32, ext2, ext3, etc., number of partitions...)
- Can you please try to open the same database from another location on your phone e.g. home folder (/home/nemo/). Does it work?

It could be that it is a SD card setup problem or something is wrong with ownKeepass trying to read from SD card.

**Comment by pottcpp** [comment] 2015-05-26 20:15
* the sd card is formatted with FAT32
* copied file in home dir does not work, too (so the sd-card is out)
* if I remember it right, the database was created with the original Windows version of Keepass1 and is now edited with Keepass1 on Windows and more often with KeepassX on OS X.
* On Blackberry there is a KeePassDroid clone in the store that can't open the database since the last app update, too. Keeps can still open it.

Error message on the screen is "hash test failed".

Are there any logs that would help you?

**Comment by jobe-m** [comment] 2015-05-26 20:53
Ok, thanks for the info.
So it seems that the database itself has a problem. I just searched a bit and found on the keepassx.org page a statement from a user: "KeePassX 0.4.3 will not open databases saved by KeePass Droid 1.99.1." So Keepass Droid from that version up manipulates the database in a way so that KeepassX 0.4.3 can't open it. This is also valid for ownKeepass since it uses the database code from 0.4.3.

On keepass.info I saw that there is a new version (1.29) of the original Keepass application. So that might also affect the database.

Could you try to open the database in KeepassX 0.4.3 and save it (with a small change). Then try to open it in ownKeepass? Maybe that healths the database structure.
I could install the original version (1.29) of Keepass in my virtualbox windows and try to reproduce if the new Keepass version is the source of the problem.

**Comment by jobe-m** [comment] 2015-05-26 21:12
I just installed Keepass 1.29. Created a new database with password and key file. Copied it to my linux host and jolla phone and could successfully open it with KeepassX 0.4.3 and ownKeepass.

So probably Keepass Droid >= 1.99.1 might be the problem. I need to reactivate my old Nexus 7 and test it ;) Later...

**Comment by jobe-m** [comment] 2015-05-26 21:29
I installed KeepassDroid 2.0.3 (newest version) for Android. And indeed after manipulating a keepass database with it ownKeepass cannot open it anymore. So something is wrong with KeepassDroid as even the original Windows Keepass application does not harm the database!

I think I will place somewhere a warning label...

**Comment by pottcpp** [comment] 2015-05-27 07:12
Just to make that clear: I did not alter the database with KeepassDroid, just used it read-only. I just mentioned it because you may share some of the code.

**Comment by jobe-m** [comment] 2015-05-28 07:59
Is it possible that you try to reproduce the problem?
You could create a new keepass database without any personal information in it.
Open and save it with all your Keepass applications which you have.
If then the database does not open in ownKeepass please send it to me with the password and key file (if used). Thanks.

**Comment by pottcpp** [comment] 2015-06-13 10:18
Hi,

I will try and report back. This may take some time, as I need to create a database with the bug ;-)

**Comment by jobe-m** [comment] 2015-06-14 20:39
*Damn* I didn't remember it until now but I had also once the situation that my database was not able to open on the jolla phone with ownKeepass. I thought that my ownCloud server was the source of the fault which I am using to sync between my desktop and jolla phone. But unfortunately I did not check that deeper. So I am not sure that maybe the fault was with ownKeepass. I just copied the file again from my desktop to my ownCloud folder so that ownKeepass could open it again... I guess that might have been the same situation as you now have. Let's see if that happens again. At least then I will take a deeper look at it...

Did anyone else see that problem, too? If yes, please check if the database can be opened with KeepassX 0.4.3, because then the fault is with the little modifications which I did to the original KeepassX 0.4.3 sources.

**Comment by jobe-m** [comment] 2015-06-14 21:18
I found the not working database in the history of file versions within my ownCloud server. (Version control FTW!) But it seems that something corrupted that file. Maybe a malicious file sync within ownCloud or SD card write problem within my ownCloud server (a Sheevaplug device). At least I cannot open that database with KeepassX 0.4.3. Also Keepass 1 on Windows and import function of KeepassX 2 Alpha 6 on Linux does not open that file, too. Always the more or less same error message:  "hash test failed", "key file/password wrong", "can't create cipher stream", ...

**Comment by jobe-m** [comment] 2015-08-18 12:35
Closing this issue as it seems to be not reproducible

**Closed by jobe-m** 2015-08-18 12:35 UTC
Labels: Bug
